#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Performing a 301 Redirection
sudo sed -i "/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }" /etc/nginx/sites-available/default

# Restarting Nginx service
service nginx start