#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
# Creating a 404 Custom error page
if ! grep -q "error_page 404 /error_404.html;" /etc/nginx/sites-available/default; then
  # Modify the Nginx default server configuration
  sudo sed -i '/server_name _;/a \
          error_page 404 /error_404.html;\n \
          location = /error_404.html {\n \
              root /var/www/html;\n \
          }\n' /etc/nginx/sites-available/default
fi 

# restart nginx after implementing changes
service nginx start