#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
defaults
    log     global
    mode    http
    option  httplog
    timeout client     15s
    timeout connect    10s
    timeout server     15s
    timeout http-request 10s

frontend my-frontend
    bind *:80
    default_backend my-backend

backend my-backend
    balance roundrobin
    server 531177-web-01 34.224.94.99:80 check
    server 531177-web-02 35.153.16.238:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
